version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    ports:
      - "5432"
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678

  spring-app:
    build: ./
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres-db:5432/tasks
      DB_USERNAME: postgres
      DB_PASSWORD: 12345678
      CORS_ORIGENS: http://localhost:8080

    depends_on:
      - postgres-db